[(1, 'computers & internet', 'computers-internet'),
 (2, 'technology', 'technology'),
 (3, 'home & garden', 'home-garden'),
 (4, 'work & money', 'work-money'),
 (5, 'sports, hobbies, & recreation', 'sports-hobbies-recreation'),
 (6, 'society & culture', 'society-culture'),
 (7, 'travel & transportation', 'travel-transportation'),
 (8, 'science & nature', 'science-nature'),
 (9, 'education', 'education'),
 (10, 'health & fitness', 'health'),
 (11, 'shopping', 'shopping'),
 (12, 'food & drink', 'food-drink'),
 (13, 'writing & language', 'writing-language'),
 (14, 'human relations', 'human-relations'),
 (15, 'media & arts', 'media-arts'),
 (16, 'pets & animals', 'pets-animals'),
 (17, 'religion & philosophy', 'religion-philosophy'),
 (18, 'clothing, beauty, & fashion', 'clothing-beauty-fashion'),
 (19, 'law & government', 'law-government'),
 (20, 'grab bag', 'grab-bag')
 ]
